// menu-crm/src/components/ImageUpload.tsx
"use client";

import { useState } from "react";

type Props = {
  inputName?: string;
  initialPath?: string;
};

export function ImageUpload({ inputName = "imagePath", initialPath = "" }: Props) {
  const [path, setPath] = useState(initialPath);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  async function onFile(f: File | null) {
    setErr(null);
    if (!f) {
      return;
    }
    setBusy(true);
    try {
      const fd = new FormData();
      fd.set("file", f);
      const res = await fetch("/api/admin/upload", { method: "POST", body: fd });
      const data = (await res.json()) as { ok?: boolean; path?: string; error?: string };
      if (!res.ok || !data.ok || !data.path) {
        throw new Error(data.error ?? "Ошибка загрузки");
      }
      setPath(data.path);
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Ошибка");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="space-y-2">
      <input type="hidden" name={inputName} value={path} />
      <input
        type="file"
        accept="image/jpeg,image/png,image/webp"
        disabled={busy}
        onChange={(e) => void onFile(e.target.files?.[0] ?? null)}
        className="block w-full text-sm text-muted file:mr-3 file:rounded-lg file:border-0 file:bg-chip file:px-3 file:py-2 file:text-sm file:font-medium file:text-accent"
      />
      {busy ? <p className="text-xs text-muted">Загрузка…</p> : null}
      {err ? <p className="text-xs text-accent">{err}</p> : null}
      {path ? (
        <div className="flex items-center gap-3">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={path} alt="" className="h-20 w-20 rounded-xl border border-line object-cover" />
          <button
            type="button"
            className="text-xs text-muted underline"
            onClick={() => setPath("")}
          >
            убрать фото из формы
          </button>
        </div>
      ) : null}
    </div>
  );
}

// admin/src/components/ImageUpload.vue
<script setup lang="ts">
import { ref } from 'vue'
import axios from 'axios'

const props = defineProps<{
  modelValue?: string
  label?: string
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const busy = ref(false)
const error = ref('')

async function onFile(event: Event) {
  const input = event.target as HTMLInputElement
  const file = input.files?.[0]
  input.value = ''
  if (!file) return

  busy.value = true
  error.value = ''
  try {
    const fd = new FormData()
    fd.append('file', file)
    const { data } = await axios.post<{ ok: boolean; path?: string; error?: string }>(
      '/api/admin/upload',
      fd,
      { withCredentials: true },
    )
    if (!data.ok || !data.path) {
      throw new Error(data.error ?? 'Не удалось загрузить файл')
    }
    emit('update:modelValue', data.path)
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Ошибка загрузки'
  } finally {
    busy.value = false
  }
}

function clear() {
  emit('update:modelValue', '')
}
</script>

<template>
  <div class="image-upload">
    <label v-if="label" class="image-upload__label">{{ label }}</label>
    <input
      type="file"
      accept="image/jpeg,image/png,image/webp"
      class="image-upload__input"
      :disabled="busy"
      @change="onFile"
    />
    <p v-if="busy" class="image-upload__hint">Загрузка…</p>
    <p v-if="error" class="image-upload__error">{{ error }}</p>
    <div v-if="modelValue" class="image-upload__preview">
      <img :src="modelValue" alt="Превью" />
      <button type="button" class="image-upload__clear" @click="clear">Убрать</button>
    </div>
  </div>
</template>

<style scoped>
.image-upload {
  display: grid;
  gap: 8px;
}

.image-upload__label {
  font-size: 14px;
  font-weight: 500;
}

.image-upload__input {
  font-size: 14px;
}

.image-upload__hint {
  margin: 0;
  font-size: 13px;
  color: #6b6560;
}

.image-upload__error {
  margin: 0;
  font-size: 13px;
  color: #b42318;
}

.image-upload__preview {
  display: flex;
  align-items: center;
  gap: 12px;
}

.image-upload__preview img {
  width: 96px;
  height: 96px;
  object-fit: cover;
  border-radius: 12px;
  border: 1px solid #e8e2da;
}

.image-upload__clear {
  border: 0;
  background: none;
  color: #6b6560;
  font-size: 13px;
  text-decoration: underline;
  cursor: pointer;
  padding: 0;
}
</style>
